pyvec/python.cz

pythoncz/static/data/business.geojson
Ahoj, Leadhub je náš startup - CRM pro e-shopy s vychytávkami pro marketing automatization. Backend máme převážně v Pythonu. Zatím to nemáme veřejně spuštěné, takže aktuální web je hodně provizorní :)
=> Přidání společnosti Leadhub s.r.o.

.travis.yml, README.md, pythoncz/__init__.py, pythoncz/views.py, runserver.py
See commits for details. The subdomains stuff is untested :smirk:
=> Various improvements

pythoncz/templates/beginners_cs.html
There is a broken link to Google Python Style Guide. I found the new one.
=> Change the old ULR of Google Python Style Guide

pythoncz/views.py
without it /zapojse/ won't redirect, only /zapojse
=> Fix missing dash

pythoncz/models/github.py, pythoncz/templates/_base.html, pythoncz/templates/get_involved_cs.html, pythoncz/templates/index_cs.html, pythoncz/templates/jobs_cs.html, pythoncz/templates/jobs_en.html
- Update Leaflet to 1.0.2. The old CDN doesn't support HTTPS, so I copied the
current URLs from the Leaflet site and checked it still works.
- Update JQuery URL to HTTPS. This should help prevent mixed-content warnings.
- Switch links to pyvo.cz to use HTTPS.
Related: https://github.com/pyvec/python.cz/issues/92
=> Use https: instead of http: in some places

README.md, pythoncz/models/github.py, pythoncz/models/github_get_issues.graphql, pythoncz/templates/get_involved_cs.html, requirements.txt
Using GitHub's new [GraphQL API (v4)](https://developer.github.com/v4/), the page can now perform just two HTTP requests (for each GitHub organization) instead of requesting each GitHub issue separately.
I removed assignee, because there can be more then one now and I wasn't sure about how important the information is. Added participants instead.
There are no tests, because I did not have time to add them. Working with GraphQL was rather exploration & prototyping and as soon as I have something working, I'm sending it as a Pull Request, because anything is better then what's on the page right now (503 HTTP error). Whoever wants to add tests, using [responses](https://github.com/getsentry/responses) would probably be a smart choice.
=> Fix performance of the 'Zapoj se' page

pythoncz/templates/beginners_cs.html
PEP8 na python.org neni uplne citelny. Myslim, ze by byl lepsi link na stranku pep8.org :).
=> Changed link to pep8

.travis.yml
Když už máme na Slacku tu `#python-cz-web` místnost, možná by se hodilo vědět, když spadne `master`...
=> Add Slack integration

pythoncz/templates/beginners_cs.html
http://pyladies.cz/course.html leads to a deprecated version of materials
This is more conservative change from https://github.com/pyvec/python.cz/pull/242
=> Fix materials link

pythoncz/static/data/business.geojson, pythoncz_tests/static/data/geojson_europe_test.py
Chtěl jsem přidat pár firem na mapku zaměstnavatelů podle nalezených inzerátů, ale přitom je neduplikovat. Naštěstí geojson podporuje multipoint, což by mohlo být řešením pro https://github.com/pyvec/python.cz/issues/245
Adekvátně tomu jsem upravil i testy.
Omlouvám se za merge commity navíc, ale naposledy jsem přispíval na python.cz před třemi lety a nevím, jak se jich zbavit. Můžete je někdo prosím výhodit?
=> Noví zaměstnavatelé na mapce

pythoncz/models/github.py, pythoncz/models/github_get_issues.graphql, pythoncz_tests/models/github_test_fixtures.py
GitHub's GraphQL has limits on the maximum possible numbers of
returned nodes, which python.cz was exceeding by getting 50
reactions per issue (× 100 issues × 100 repositories).
Summarize the reactions by only getting the total number and
totals of the "downvoting" ones.
This lets us bump the number of labels per issue from 5 to 20.
Same for pull requests.
Fixes: https://github.com/pyvec/python.cz/issues/250
=> Make the issue list work again

pythoncz/static/main.css, pythoncz/templates/_events.html, pythoncz/views.py
- In the English version, use English weekday names 
- Make boxes for tentative events smaller
=> De-emphasize tentative events

pythoncz/models/github_get_issues.graphql
A poor trial & error attempt to make the query more efficient.
=> Lower numbers in the GraphQL query

Pipfile, Pipfile.lock, pythoncz/models/github.py, tests/models/github_test.py, tests/views_test.py
In version 1.0 the contrib part of werkzeug has been completely removed. The caching utilities has been moved to a package called cachelib.
=> Replace werkzeug.contrib with cachelib

.travis.yml
The [Travis docs](https://docs.travis-ci.com/user/deployment/) and [Elsa docs](https://github.com/pyvec/elsa/blob/master/README.rst#travis-ci-based-deployment) have `skip_cleanup`.
As far as I can see, this was changed in https://github.com/pyvec/python.cz/pull/404, which removed the config for [dpl v1](https://docs.travis-ci.com/user/deployment/) without switching to [dpl v2 beta](https://docs.travis-ci.com/user/deployment-v2).
=> .travis.yml: Use skip_cleanup rather than cleanup

pythoncz/models/github_get_issues.graphql
- Limit all the collections to first 20 items.
GitHub paginates by 20 items; unless we follow that we might as well
limit the query.
- Exclude locked (archived) and private repositories
- Order things by last update date, so we hopefully get relevant ones in
cases when some are hidden. (It's not possible to order by "popularity",
see: https://docs.github.com/en/graphql/reference/enums#issueorderfield )
=> zapojse: limit the GraphQL query

pythoncz/templates/_base.html, pythoncz/templates/_communication.html, pythoncz/templates/index_cs.html
This is a breaking change and should be thoroughly tested/reviewed.
What seems to break the most are icons as some of them were renamed or categorized differently
(example: `fa fa-facebook` vs `fab fa-facebook`) in FA 5, I tried to spot as much as possible but still there might 
be stuff I missed.
=> Upgrade Font Awesome to version 5

pythoncz/templates/_communication.html
1. Pyonýři (IMHO most mainstream)
2. Discord (shiny new stuff)
3. e-mail groups (still surviving)
4. twitter accounts
5. irc channels (almost dead? IDK)
6. slack (invite-only, for orgs/admins/mods, not interesting that much for regular community members)
Also, I've removed Pyvec Twitter as it's not very interesting and maintained. I've replaced it with PyLadies CZ Twitter.
=> Reorder and update links

pythoncz/static/data/business.geojson
At Leadspicker we have almost all code in Python (Django) and we are always looking for pythonistas :)
We are struggling a bit with HR (do not currently have dedicated person for that) and our advert on StartupJobs expired (again), so I have only this link for now https://www.startupjobs.cz/nabidka/30347/python-django-developer-wanted
=> Added Leadspicker to business.geojson

pythoncz/models/github_get_issues.graphql, pythoncz/static/data/events_feeds.yml
python.cz needs some more love, but it's better for comtributors to start with something that works :)
=> Hotfixes to make the site build
