pyvec/python.cz

index.html
> Ahoj, prosímtě, nevadilo by Ti dodat link na mnou hostovaný článek
> http://macek.sandbox.cz/texty/prvni-jazyk-python/ mezi české čtení na
> python.cz?
>
> Forkovat celé repo kvůli jednomu řádku mám poněkud za overhead. :-)
>
> Díky za zvážení,
>
=> Article from Vladimir Macek

pythoncz/static/data/business.geojson
Both Webexpo and Red Hat have another entry.
=> business.geojson: remove duplicate Webexpo entry

pythoncz/static/data/business.geojson
Added tcp cloud company, which develops OpenStack modules and other support applications in python.
=> tcp cloud a.s

pythoncz/models/jobs.py, pythoncz/static/main.css, pythoncz/templates/get_involved_cs.html
fixing #82 
takhle by to stacilo? nastavil jsem fixni vysku boxum a kdyz je text delsi, tak je pres nej hozen stin. zaroven se zobrazuje po najeti kurzorem title s celym textem
=> fix tasks floating and overflow issues

pythoncz/static/data/beginners.yml
Navrhuji přidat předměty, ve kterých učím Python.
=> Přidány předměty na ZČU v Plzni

pythoncz/static/data/jobs.yml
=> Added interview questions by TopTal

pythoncz/static/data/jobs.yml
=> Fixed case

pythoncz/templates/beginners_cs.html
=> Odkaz na materiály na PyLadies

pythoncz/templates/_base.html
We really should thank the nice people who let us host python.cz!
=> Thank the website's sponsors

pythoncz/templates/beginners_cs.html
Koukal jsem na verzi Pythonu a vypadá to, že používají 3. Link je filtr na videa, která jsou česky nebo anglicky a je tam filtr na Python.
=> Různé úvodní lekce od Microsoft Virtual Academy

pythoncz/static/data/beginners.yml
Z anotace:
> Hlavní motivací je naučit studenty přemýšlet o problémů inženýrským způsobem. Rozmýšlení úlohy, dekompozice, definování rozhraní, způsob testování jednotlivých mezikroků, ověření a testování úspěšnosti celé úlohy.
Na kurzu se programuje právě především v Pythonu.
=> Odkaz na kurz A4B99RPH na ČVUT FEL

pythoncz/static/data/business.geojson
=> Pridani firmy Direct-services s.r.o.

pythoncz/static/data/business.geojson
=> Added ROI Hunter into companies

pythoncz/static/data/business.geojson
=> Pridanie firmy na mapu a do zoznamu

pythoncz/static/data/business.geojson
On uz vo WTF nerobi a WTF sa zmenila na digitalnu agenturu :)
=> Removed Jozef Simo from list of persons

pythoncz/templates/beginners_cs.html
=> Linking Czech version of the Django Girls tutorial

pythoncz/static/data/beginners.yml
👠 
------
Closes https://github.com/pyvec/python.cz/issues/123
Closes https://github.com/pyvec/python.cz/issues/106
=> Add courses for ladies

pythoncz/templates/beginners_cs.html
=> Add Code School

pythoncz/templates/_base.html
=> Updated footer info

pythoncz/static/data/beginners.yml
I couldn't choose a suitable category so I created a new one. I am also not very confident with my czech language skills.
=> Add pythonvikend organized by kiwi.com

pythoncz/templates/beginners_cs.html
See [this](https://www.facebook.com/groups/pyonieri/permalink/1200809076597934/?comment_id=1200907663254742&comment_tracking=%7B%22tn%22%3A%22R%22%7D) for reasoning.
=> Proposal: Reword how tutorials are promoted

pythoncz/__init__.py, pythoncz/templates/index_cs.html, pythoncz/views.py
=> Redirect the original URL

pythoncz/views.py
=> Fix view name (to match the one in template)

pythoncz/static/data/business.geojson
Hello, I would like to add our company to the list of python users. Thank you very much
=> Add SparkTECH company to the list of python users

pythoncz/static/data/business.geojson
=> Added Petr Blahos as an individual

pythoncz/static/data/business.geojson
=> Fix: Petr Blahos's website is not on https.

pythoncz/templates/index_cs.html
mi tam chybi casto a i jinym lidem.
=> Příručka pro pořadatele

.travis.yml
=> Production Python version is 3.4, let's save CI time

pythoncz/static/images/uk-flag.svg, pythoncz/static/main.css, pythoncz/templates/beginners_cs.html
Also move courses to the bottom. They need to get reorganised
(#105, #140), the display doesn't really fit the data and currently
I'd say it's more important to emphasize the online resources. YMMV
Close https://github.com/pyvec/python.cz/issues/80
=> Use UK flag to denote links to English resources

README.md, deployment/README.md, pythoncz/__init__.py, pythoncz/models/beginners.py, pythoncz/models/github.py, pythoncz/models/jobs.py, pythoncz/static/main.css, pythoncz/templates/get_involved_cs.html, pythoncz/templates/index_cs.html, pythoncz/templates/jobs_cs.html, pythoncz/templates/jobs_en.html, pythoncz/views.py
Production server is already prepared for these changes (`GITHUB_TOKEN` is set in Supervisor), so this can be merged right away if acceptable. Closes https://github.com/pyvec/python.cz/issues/151, https://github.com/pyvec/python.cz/issues/150, https://github.com/pyvec/python.cz/issues/147, https://github.com/pyvec/python.cz/issues/144, https://github.com/pyvec/python.cz/pull/157. Couple of screenshots:
-----------
-----------
=> Renew Zapoj se page

.gitignore, deployment/update.sh, pythoncz/__init__.py, pythoncz/models/github.py, pythoncz/static/main.css
Making https://github.com/pyvec/python.cz/pull/169 great again. Previously I correctly set `GITHUB_TOKEN` environment variable in Supervisord's configuration, but I did not reload supervisord to pick up the configuration. Now everything is prepared.
Closes https://github.com/pyvec/python.cz/issues/150. Implements some items from https://github.com/pyvec/python.cz/issues/170.
=> Zapoj se II.

pythoncz/static/data/business.geojson
přesunuty firmy z Jemenu zpět k nám - řeší #172
=> Jemen -> Česká republika

README.md, deployment/README.md, pythoncz/__init__.py, pythoncz/models/beginners.py, pythoncz/models/jobs.py, pythoncz/templates/get_involved_cs.html , pythoncz/templates/index_cs.html, pythoncz/templates/jobs_cs.html, pythoncz/templates/jobs_en.html, pythoncz/views.py
(git overwritten @encukou's revert over all my changes when I was rebasing against master)
Related to https://github.com/pyvec/python.cz/pull/169 and https://github.com/pyvec/python.cz/pull/175.
=> Getting back all my changes

pythoncz/models/github.py
Closes https://github.com/pyvec/zapojse/issues/47
=> Fix repo URL

pythoncz/static/main.css, pythoncz/templates/_base.html
Added notice on every page that people should fill the meetups feedback form. **This must not be merged before https://github.com/pyvec/pyvo.cz/pull/39 is merged and deployed.**
=> Zpětnovazebník

pythoncz/static/data/business.geojson
Closes https://github.com/pyvec/python.cz/issues/137
=> Add jack.cz

app.py, pythoncz/views.py, runserver.py
Supersedes parts of https://github.com/pyvec/python.cz/pull/104, closes https://github.com/pyvec/python.cz/issues/98.
=> Redirect www

tests/geojson_europe_test.py, tests/valid_json_test.py, tests/valid_yaml_test.py
=> Applying new knowledge I learned on a meetup

pythoncz/templates/beginners_cs.html
- The Czech version is beta and according to some reports it's starting to lack behind the EN one
- Even if Czech was up-to-date, someone might want to prefer Slovak or Polish (quite common in Silesia) instead
=> Let the reader to choose their language

pythoncz/models/github.py, requirements.txt
Changes the response time for me from ~1.5 minutes to 10 seconds
Should fix the 502 Bad Gateway indicated in
https://github.com/pyvec/python.cz/issues/188#issuecomment-282834171
=> Use grequests to get all issues details asynchronously

pythoncz/templates/jobs_cs.html, pythoncz/templates/jobs_en.html
=> Add PyCon CZ and PyCon SK as hiring opportunities

pythoncz/static/data/business.geojson
Note sure if adding a Slovak company is ok, but there are already a few. We have a small office in Prague as well, but development is done in bratislava.
=> Add exponea.com

.travis.yml, README.md, pythoncz/models/github.py, pythoncz_tests/models/github_test.py, setup.cfg, setup.py
Followup for #211 
To be autosquashed once merged to #211
=> Followup for #211

README.md, pythoncz_tests/models/github_test.py
=> Followup for #211 #212

README.md
Closes https://github.com/pyvec/python.cz/issues/202
=> Explain why the GitHub token is needed

pythoncz/static/data/business.geojson
Closes https://github.com/pyvec/python.cz/issues/200
=> Add MSD to list of companies

pythoncz_tests/models/github_test.py
Adds test for https://github.com/pyvec/python.cz/pull/219
=> Add test for sprint-idea label

pythoncz/static/main.css, pythoncz/templates/get_involved_cs.html, pythoncz/views.py, pythoncz_tests/models/github_test.py, pythoncz_tests/views_test.py
- Fixes legacy redirect from `index.html`
- Closes https://github.com/pyvec/python.cz/issues/192
- Closes https://github.com/pyvec/python.cz/issues/191
=> Add more tests

pythoncz/static/data/business.geojson
Tak jsme sice s @messa udělali včera první Pull Request letošního sprintu - https://github.com/pyvec/python.cz/pull/217, ale review jsme dělali už v pokročilé fázi večera a tudíž se nám povedlo zmást o kterou firmu jde. Díky @lspdv za upozornění. Cílem bylo přidat to MSD, které se jmenuje MSD IT a má sídlo na břehu Vltavy, a to jsme dopletli. V původním issue to nebylo napsáno a @messa to neměl jak vědět a prošlo to přes mé nedostatečné review.
Co se týče approvalu od samotné firmy, tak bych si dovolil tvrdit, že seznam firem na Python.cz tradičně funguje způsobem
```
try:
přidej firmu, o které víš, že používá Python
except:
vyřeš případný problém
```
Lidskou řečí - přidáváme firmy intuitivně a až ve chvíli, kdy by jim to vadilo, nebo chtěli něco změnit, nebo v seznamu vůbec nechtěly být, …
=> Fix MSD entry

pythoncz/templates/beginners_cs.html
https://github.com/pyvec/python.cz/issues/206
Zároveň jsem ty boxíky s kurzy udělal širší :)
Předtím:
Potom:
=> Přidat odkaz na FB skupinu Učíme Python

pythoncz/static/data/business.geojson
=> Add SpaceKnow to the list of companies

pythoncz/templates/_meetups.html
* add Liberec meetup
* add Plzeň meetup
=> Add meetups

pythoncz/static/main.css, pythoncz/templates/_base.html
This reverts "removed zpetnovazebnik" and builds on top of it.
This reverts commit b35ce40fed9e8376b06bf27f5482751ebf7b40fb.
=> Add a note about the community sprint

pythoncz/models/github.py
*If the implementation is hard to explain, it's a bad idea.* Viz diskuse u https://github.com/pyvec/python.cz/pull/262/files/76c878d31f92e33d7edab81958fc4a08fb63d08a#diff-52bb6addd2439696fab4e624c6894d7e
Díky Mirovi za to jednoduché shrnutí! Něco takhle úderného jsem tam chtěl napsat, ale měl jsem plnou hlavu implementace :)
---
To mě ale přivádí k otázce: je tahle logika správná? Když někdo nahlásí "Tahle stránka vůbec nefunguje" a lidi k tomu dají :-1::-1::-1:, nemělo by se to počítat jako hlasy *pro* vyřešení toho problému?
=> Pochopitelnější logika hlasování pro issues/PRs

.travis.yml
https://docs.travis-ci.com/user/notifications/
=> Make Slack notifications less noisy

pythoncz/static/data/business.geojson
Už jsme se zase přestěhovali...
=> Aktualizace pozice SparkTECHu

pythoncz/static/data/events_feeds.yml
=> Add PyData Prague among displayed events

pythoncz/models/events.py, pythoncz/static/main.css, pythoncz/templates/_events.html, pythoncz/templates/events_cs.html, pythoncz/templates/events_en.html, pythoncz/views.py, tests/models/events_test.py
Might be worth reviewing commit-by-commit, tackles multiple issues.
=> Improve events

pythoncz/templates/index_cs.html, pythoncz/templates/index_en.html
=> Link to the new Bookshelf

pythoncz/static/data/business.geojson
=> Add H2O.ai

pythoncz/models/meetups.py
The Wikipedia page has been erroneously edited by someone and Liberec is now missing from the list of cities.
=> Avoid hitting Wikipedia

pythoncz/static/data/business.geojson
=> Změna odkazu na Mergado

pythoncz/static/data/business.geojson
=> Add Colpirio.com s.r.o.

pythoncz/static/data/business.geojson
Both companies have same address and specialize in cyber security and Python programming.
=> Adding ICT & MEDIA and REDAMP companies

pythoncz/static/data/business.geojson
https://www.startupjobs.cz/admin/neuron-soundware/profil
Diky!
=> add Neuron soundware

pythoncz/models/github_get_issues.graphql
This should fix `Parse error on ")" (RPAREN) at [25, 23]` coming from GitHub.
Fixes: https://github.com/pyvec/python.cz/issues/416
=> Fix GraphQL for GitHub issues

.github/workflows/main.yml
=> Build only on push

.github/workflows/main.yml
=> Revert "Build only on push"

pythoncz/templates/_communication.html
I've generated custom invite link that will never expire not is limited by users.
Depends on #447 
Resolves #401
=> Add link to discord 

README.md, pythoncz/__init__.py, pythoncz/templates/_base.html
See https://pyvec.slack.com/archives/C12MP1GDB/p1635765591005700
=> Replace GA with SA

README.md
As I previously announced, I currently don't have the time to improve this project. As it is an important project for the community, I think I shouldn't give the impression I do maintain the repo or that my opinions should be taken into account if anyone wants to step in and take over the repo. I want to clearly communicate that this is now up to grabs for anyone with at least a little bit of courage and vision.
=> Step down as a maintainer
